name : README

on:
    push:
        paths:
            -   docs/Helpers.yaml
            -   docs/Sponsors.yaml
            -   docs/Template.md

jobs:
    Update-README:
        runs-on : ubuntu-latest
        steps:
            
            -   uses : denoland/setup-deno@v1
                with:
                    deno-version : 1.23.4
                    
            -   run : ls
            
            -   run : ls scripts
            
            -   run : ls scripts/README
                
            -   name : Run README updater
                run : 'deno run 
                    --allow-read 
                    --allow-write 
                    --importmap=scripts/README/Imports.json 
                    scripts/README/Updater.js'
